
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.rule
{
public sealed partial class RuleTips : Luban.BeanBase
{
    public RuleTips(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static RuleTips DeserializeRuleTips(JSONNode _buf)
    {
        return new rule.RuleTips(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -1046062298;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

