
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.rule
{
public partial class TbRuleTips
{
    private readonly System.Collections.Generic.Dictionary<int, rule.RuleTips> _dataMap;
    private readonly System.Collections.Generic.List<rule.RuleTips> _dataList;
    
    public TbRuleTips(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, rule.RuleTips>();
        _dataList = new System.Collections.Generic.List<rule.RuleTips>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            rule.RuleTips _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = rule.RuleTips.DeserializeRuleTips(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, rule.RuleTips> DataMap => _dataMap;
    public System.Collections.Generic.List<rule.RuleTips> DataList => _dataList;

    public rule.RuleTips GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public rule.RuleTips Get(int key) => _dataMap[key];
    public rule.RuleTips this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

