
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.attr
{
public sealed partial class Attribute : Luban.BeanBase
{
    public Attribute(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["attr_type"].IsNumber) { throw new SerializationException(); }  AttrType = _buf["attr_type"]; }
    }

    public static Attribute DeserializeAttribute(JSONNode _buf)
    {
        return new attr.Attribute(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly int AttrType;
   
    public const int __ID__ = -802488641;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "attrType:" + AttrType + ","
        + "}";
    }
}

}

