
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public ui.TbUiView TbUiView {get; }
    public attr.TbAttribute TbAttribute {get; }
    public ratio.TbRatioAttr TbRatioAttr {get; }
    public rule.TbRuleTips TbRuleTips {get; }
    public crtag.TbRoleTag TbRoleTag {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbUiView = new ui.TbUiView(loader("ui_tbuiview"));
        TbAttribute = new attr.TbAttribute(loader("attr_tbattribute"));
        TbRatioAttr = new ratio.TbRatioAttr(loader("ratio_tbratioattr"));
        TbRuleTips = new rule.TbRuleTips(loader("rule_tbruletips"));
        TbRoleTag = new crtag.TbRoleTag(loader("crtag_tbroletag"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbUiView.ResolveRef(this);
        TbAttribute.ResolveRef(this);
        TbRatioAttr.ResolveRef(this);
        TbRuleTips.ResolveRef(this);
        TbRoleTag.ResolveRef(this);
    }
}

}
