
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.crtag
{
public sealed partial class RoleTag : Luban.BeanBase
{
    public RoleTag(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["attr_type"].IsNumber) { throw new SerializationException(); }  AttrType = _buf["attr_type"]; }
        { if(!_buf["drop_num"].IsNumber) { throw new SerializationException(); }  DropNum = _buf["drop_num"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["action_num"].IsNumber) { throw new SerializationException(); }  ActionNum = _buf["action_num"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
    }

    public static RoleTag DeserializeRoleTag(JSONNode _buf)
    {
        return new crtag.RoleTag(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly int AttrType;
    /// <summary>
    /// 触发点
    /// </summary>
    public readonly int DropNum;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 行动
    /// </summary>
    public readonly int ActionNum;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
   
    public const int __ID__ = -1199259391;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "attrType:" + AttrType + ","
        + "dropNum:" + DropNum + ","
        + "desc:" + Desc + ","
        + "actionNum:" + ActionNum + ","
        + "quality:" + Quality + ","
        + "}";
    }
}

}

