
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.crtag
{
public partial class TbRoleTag
{
    private readonly System.Collections.Generic.Dictionary<int, crtag.RoleTag> _dataMap;
    private readonly System.Collections.Generic.List<crtag.RoleTag> _dataList;
    
    public TbRoleTag(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, crtag.RoleTag>();
        _dataList = new System.Collections.Generic.List<crtag.RoleTag>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            crtag.RoleTag _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = crtag.RoleTag.DeserializeRoleTag(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, crtag.RoleTag> DataMap => _dataMap;
    public System.Collections.Generic.List<crtag.RoleTag> DataList => _dataList;

    public crtag.RoleTag GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public crtag.RoleTag Get(int key) => _dataMap[key];
    public crtag.RoleTag this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

