
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ratio
{
public sealed partial class RatioAttr : Luban.BeanBase
{
    public RatioAttr(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["attr_str"].IsString) { throw new SerializationException(); }  AttrStr = _buf["attr_str"]; }
    }

    public static RatioAttr DeserializeRatioAttr(JSONNode _buf)
    {
        return new ratio.RatioAttr(_buf);
    }

    /// <summary>
    /// 唯一标识
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 比例换算
    /// </summary>
    public readonly string AttrStr;
   
    public const int __ID__ = -733015463;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "attrStr:" + AttrStr + ","
        + "}";
    }
}

}

