
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ratio
{
public partial class TbRatioAttr
{
    private readonly System.Collections.Generic.Dictionary<int, ratio.RatioAttr> _dataMap;
    private readonly System.Collections.Generic.List<ratio.RatioAttr> _dataList;
    
    public TbRatioAttr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ratio.RatioAttr>();
        _dataList = new System.Collections.Generic.List<ratio.RatioAttr>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ratio.RatioAttr _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ratio.RatioAttr.DeserializeRatioAttr(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ratio.RatioAttr> DataMap => _dataMap;
    public System.Collections.Generic.List<ratio.RatioAttr> DataList => _dataList;

    public ratio.RatioAttr GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ratio.RatioAttr Get(int key) => _dataMap[key];
    public ratio.RatioAttr this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

