
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ui
{
public partial class TbUiView
{
    private readonly System.Collections.Generic.Dictionary<string, ui.UIView> _dataMap;
    private readonly System.Collections.Generic.List<ui.UIView> _dataList;
    
    public TbUiView(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, ui.UIView>();
        _dataList = new System.Collections.Generic.List<ui.UIView>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ui.UIView _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ui.UIView.DeserializeUIView(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ViewName, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, ui.UIView> DataMap => _dataMap;
    public System.Collections.Generic.List<ui.UIView> DataList => _dataList;

    public ui.UIView GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ui.UIView Get(string key) => _dataMap[key];
    public ui.UIView this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

